services:
  sereni-storage-provider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sereni-storage-provider
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - sereni-network
    depends_on:
      - rustfs

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "9000:9000"     # S3 API endpoint
      - "9001:9001"     # Web Console UI
    environment:
      # Configures logical storage volumes inside the mapped directory
      - RUSTFS_VOLUMES=/data/rustfs{0..3}
      # Local dev only: all test volumes are on the same host disk.
      - RUSTFS_UNSAFE_BYPASS_DISK_CHECK=true
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      # Root Admin Credentials
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - sereni-network

networks:
  sereni-network:
    driver: bridge
