sonar.projectKey=aptlogica_sereni-storage-provider_268fdb46-e26c-4658-8e95-7ad63d65f666

sonar.language=go
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.exclusions=Dockerfile
 
