sonar.projectKey=aptlogica_sereni-storage-provider
sonar.organization=aptlogica

sonar.language=go
sonar.sources=cmd,internal
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile,coverage.html,tests/**,**/*_test.go
sonar.coverage.exclusions=cmd/server/main.go,docs/**,**/docs.go