sonar.projectKey=aptlogica_sereni-storage-provider
sonar.organization=aptlogica
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile,coverage.html,**/*_test.go
 
