name: Security - Trivy

on:
  push:
    branches: [main, master, develop]
  pull_request:

permissions:
  contents: read

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.0.0

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 # v0.36.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@f205ea11db2e05a39cb2a3512a201b1e6e0d9b43 # v4.37.4
        with:
          sarif_file: trivy-results.sarif
